// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package gorpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Version              string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Id                   uint64            `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Header               map[string]string `protobuf:"bytes,4,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Method               string            `protobuf:"bytes,6,opt,name=method,proto3" json:"method,omitempty"`
	Path                 string            `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_990ecfbd3e147c60, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Request) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type Response struct {
	Version              string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Id                   uint64            `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Header               map[string]string `protobuf:"bytes,4,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Body                 []byte            `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Code                 int32             `protobuf:"varint,8,opt,name=code,proto3" json:"code,omitempty"`
	Error                string            `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_990ecfbd3e147c60, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Response) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response) GetHeader() map[string]string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "gorpc.Request")
	proto.RegisterMapType((map[string]string)(nil), "gorpc.Request.HeaderEntry")
	proto.RegisterType((*Response)(nil), "gorpc.Response")
	proto.RegisterMapType((map[string]string)(nil), "gorpc.Response.HeaderEntry")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_990ecfbd3e147c60) }

var fileDescriptor_message_990ecfbd3e147c60 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xc9, 0xff, 0x76, 0xaa, 0x22, 0x8b, 0xc8, 0x50, 0x2f, 0xc5, 0x53, 0x4f, 0x39, 0xb4,
	0x17, 0xf5, 0x2e, 0x78, 0xde, 0x6f, 0x90, 0x76, 0x87, 0xa6, 0x68, 0x33, 0x71, 0x77, 0x5b, 0xc8,
	0xd7, 0xf5, 0x93, 0xb8, 0x99, 0x44, 0x11, 0x4f, 0x4a, 0x6f, 0xef, 0xbd, 0x0c, 0x2f, 0xef, 0xc7,
	0xc2, 0xe5, 0x81, 0x9c, 0xab, 0x76, 0x54, 0xb6, 0x96, 0x3d, 0xab, 0x6c, 0xc7, 0xb6, 0xdd, 0xde,
	0x7f, 0x44, 0x50, 0x68, 0x7a, 0x3f, 0x92, 0xf3, 0x0a, 0xa1, 0x38, 0x91, 0x75, 0x7b, 0x6e, 0x30,
	0x5e, 0x44, 0xcb, 0xa9, 0xfe, 0xb2, 0xea, 0x0a, 0xe2, 0xbd, 0xc1, 0x24, 0x84, 0xa9, 0x0e, 0x4a,
	0xad, 0x20, 0xaf, 0xa9, 0x32, 0x64, 0x31, 0x5d, 0x24, 0xcb, 0xd9, 0x6a, 0x5e, 0x4a, 0x5b, 0x39,
	0x36, 0x95, 0x2f, 0xf2, 0xf1, 0xb9, 0xf1, 0xb6, 0xd3, 0xe3, 0xa5, 0x52, 0x90, 0x6e, 0xd8, 0x74,
	0x98, 0x85, 0x96, 0x0b, 0x2d, 0x5a, 0xdd, 0x42, 0x7e, 0x20, 0x5f, 0xb3, 0xc1, 0x5c, 0x7e, 0x38,
	0xba, 0xfe, 0xb6, 0xad, 0x7c, 0x8d, 0x85, 0xa4, 0xa2, 0xe7, 0x8f, 0x30, 0xfb, 0x51, 0xab, 0xae,
	0x21, 0x79, 0xa5, 0x0e, 0x23, 0xb9, 0xe8, 0xa5, 0xba, 0x81, 0xec, 0x54, 0xbd, 0x1d, 0x69, 0x1c,
	0x3f, 0x98, 0xa7, 0xf8, 0x21, 0xea, 0x21, 0x27, 0x9a, 0x5c, 0xcb, 0x8d, 0xa3, 0x7f, 0x50, 0xae,
	0x7f, 0x51, 0xde, 0x7d, 0x53, 0x0e, 0x55, 0x7f, 0xc6, 0x0c, 0xd9, 0x96, 0x0d, 0xe1, 0x24, 0x64,
	0x99, 0x16, 0xdd, 0xaf, 0x25, 0x6b, 0xd9, 0xe2, 0x74, 0x58, 0x2b, 0xe6, 0x0c, 0xc8, 0x4d, 0x2e,
	0xef, 0xba, 0xfe, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x01, 0x5a, 0x64, 0xaa, 0xe8, 0x01, 0x00, 0x00,
}
