// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package gorpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PathConfig struct {
	Domains              []string `protobuf:"bytes,2,rep,name=domains,proto3" json:"domains,omitempty"`
	Paths                []string `protobuf:"bytes,3,rep,name=paths,proto3" json:"paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PathConfig) Reset()         { *m = PathConfig{} }
func (m *PathConfig) String() string { return proto.CompactTextString(m) }
func (*PathConfig) ProtoMessage()    {}
func (*PathConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e5f23cb9002a44bb, []int{0}
}
func (m *PathConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PathConfig.Unmarshal(m, b)
}
func (m *PathConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PathConfig.Marshal(b, m, deterministic)
}
func (dst *PathConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PathConfig.Merge(dst, src)
}
func (m *PathConfig) XXX_Size() int {
	return xxx_messageInfo_PathConfig.Size(m)
}
func (m *PathConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_PathConfig.DiscardUnknown(m)
}

var xxx_messageInfo_PathConfig proto.InternalMessageInfo

func (m *PathConfig) GetDomains() []string {
	if m != nil {
		return m.Domains
	}
	return nil
}

func (m *PathConfig) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

type Config struct {
	Rules                []*PathConfig `protobuf:"bytes,2,rep,name=rules,proto3" json:"rules,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e5f23cb9002a44bb, []int{1}
}
func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (dst *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(dst, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetRules() []*PathConfig {
	if m != nil {
		return m.Rules
	}
	return nil
}

type StatusResponse struct {
	UnsedPaths           []string `protobuf:"bytes,3,rep,name=unsed_paths,json=unsedPaths,proto3" json:"unsed_paths,omitempty"`
	Domains              []string `protobuf:"bytes,4,rep,name=domains,proto3" json:"domains,omitempty"`
	Paths                []string `protobuf:"bytes,5,rep,name=paths,proto3" json:"paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e5f23cb9002a44bb, []int{2}
}
func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (dst *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(dst, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetUnsedPaths() []string {
	if m != nil {
		return m.UnsedPaths
	}
	return nil
}

func (m *StatusResponse) GetDomains() []string {
	if m != nil {
		return m.Domains
	}
	return nil
}

func (m *StatusResponse) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

type Request struct {
	Version              string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Id                   uint64            `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Uri                  []byte            `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	Method               string            `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Body                 []byte            `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	ContentType          string            `protobuf:"bytes,7,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	UserAgent            []byte            `protobuf:"bytes,8,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Cookie               map[string][]byte `protobuf:"bytes,9,rep,name=cookie,proto3" json:"cookie,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Header               map[string][]byte `protobuf:"bytes,10,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RemoteAddr           string            `protobuf:"bytes,11,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	Referer              string            `protobuf:"bytes,12,opt,name=referer,proto3" json:"referer,omitempty"`
	Received             int64             `protobuf:"varint,15,opt,name=received,proto3" json:"received,omitempty"`
	Path                 string            `protobuf:"bytes,16,opt,name=path,proto3" json:"path,omitempty"`
	Host                 string            `protobuf:"bytes,17,opt,name=host,proto3" json:"host,omitempty"`
	Form                 map[string][]byte `protobuf:"bytes,18,rep,name=form,proto3" json:"form,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Query                map[string][]byte `protobuf:"bytes,19,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Param                map[string]string `protobuf:"bytes,20,rep,name=param,proto3" json:"param,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e5f23cb9002a44bb, []int{3}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Request) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetUri() []byte {
	if m != nil {
		return m.Uri
	}
	return nil
}

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Request) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Request) GetUserAgent() []byte {
	if m != nil {
		return m.UserAgent
	}
	return nil
}

func (m *Request) GetCookie() map[string][]byte {
	if m != nil {
		return m.Cookie
	}
	return nil
}

func (m *Request) GetHeader() map[string][]byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Request) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

func (m *Request) GetReferer() string {
	if m != nil {
		return m.Referer
	}
	return ""
}

func (m *Request) GetReceived() int64 {
	if m != nil {
		return m.Received
	}
	return 0
}

func (m *Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Request) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Request) GetForm() map[string][]byte {
	if m != nil {
		return m.Form
	}
	return nil
}

func (m *Request) GetQuery() map[string][]byte {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *Request) GetParam() map[string]string {
	if m != nil {
		return m.Param
	}
	return nil
}

type Response struct {
	Version              string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Id                   uint64            `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	StatusCode           int32             `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Body                 []byte            `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Error                string            `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	Header               map[string][]byte `protobuf:"bytes,10,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ContentType          string            `protobuf:"bytes,11,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Cookies              []*Cookie         `protobuf:"bytes,12,rep,name=cookies,proto3" json:"cookies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e5f23cb9002a44bb, []int{4}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Response) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *Response) GetHeader() map[string][]byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetContentType() string {
	if m != nil {
		return m.ContentType
	}
	return ""
}

func (m *Response) GetCookies() []*Cookie {
	if m != nil {
		return m.Cookies
	}
	return nil
}

type Cookie struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Path                 string   `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Domain               string   `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	ExpiredSec           int64    `protobuf:"varint,6,opt,name=expired_sec,json=expiredSec,proto3" json:"expired_sec,omitempty"`
	Secure               bool     `protobuf:"varint,8,opt,name=secure,proto3" json:"secure,omitempty"`
	HttpOnly             bool     `protobuf:"varint,9,opt,name=http_only,json=httpOnly,proto3" json:"http_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cookie) Reset()         { *m = Cookie{} }
func (m *Cookie) String() string { return proto.CompactTextString(m) }
func (*Cookie) ProtoMessage()    {}
func (*Cookie) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_e5f23cb9002a44bb, []int{5}
}
func (m *Cookie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cookie.Unmarshal(m, b)
}
func (m *Cookie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cookie.Marshal(b, m, deterministic)
}
func (dst *Cookie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cookie.Merge(dst, src)
}
func (m *Cookie) XXX_Size() int {
	return xxx_messageInfo_Cookie.Size(m)
}
func (m *Cookie) XXX_DiscardUnknown() {
	xxx_messageInfo_Cookie.DiscardUnknown(m)
}

var xxx_messageInfo_Cookie proto.InternalMessageInfo

func (m *Cookie) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cookie) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Cookie) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Cookie) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Cookie) GetExpiredSec() int64 {
	if m != nil {
		return m.ExpiredSec
	}
	return 0
}

func (m *Cookie) GetSecure() bool {
	if m != nil {
		return m.Secure
	}
	return false
}

func (m *Cookie) GetHttpOnly() bool {
	if m != nil {
		return m.HttpOnly
	}
	return false
}

func init() {
	proto.RegisterType((*PathConfig)(nil), "gorpc.PathConfig")
	proto.RegisterType((*Config)(nil), "gorpc.Config")
	proto.RegisterType((*StatusResponse)(nil), "gorpc.StatusResponse")
	proto.RegisterType((*Request)(nil), "gorpc.Request")
	proto.RegisterMapType((map[string][]byte)(nil), "gorpc.Request.CookieEntry")
	proto.RegisterMapType((map[string][]byte)(nil), "gorpc.Request.FormEntry")
	proto.RegisterMapType((map[string][]byte)(nil), "gorpc.Request.HeaderEntry")
	proto.RegisterMapType((map[string]string)(nil), "gorpc.Request.ParamEntry")
	proto.RegisterMapType((map[string][]byte)(nil), "gorpc.Request.QueryEntry")
	proto.RegisterType((*Response)(nil), "gorpc.Response")
	proto.RegisterMapType((map[string][]byte)(nil), "gorpc.Response.HeaderEntry")
	proto.RegisterType((*Cookie)(nil), "gorpc.Cookie")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_e5f23cb9002a44bb) }

var fileDescriptor_message_e5f23cb9002a44bb = []byte{
	// 668 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x6e, 0x13, 0x31,
	0x10, 0x56, 0xfe, 0x93, 0x49, 0x5a, 0x5a, 0x53, 0x21, 0xd3, 0x0a, 0x01, 0xb9, 0xb4, 0x07, 0x14,
	0x44, 0x7b, 0xa0, 0x20, 0x2e, 0x55, 0x05, 0xe2, 0x46, 0x71, 0xb9, 0x47, 0xdb, 0xdd, 0x69, 0xb3,
	0x6a, 0x77, 0xbd, 0xd8, 0xde, 0x8a, 0xbc, 0x17, 0x37, 0x9e, 0x81, 0x77, 0xc2, 0x33, 0xde, 0x24,
	0xab, 0x50, 0x04, 0x15, 0xa7, 0xcc, 0x7c, 0x33, 0x9f, 0x77, 0x3c, 0x9e, 0x6f, 0x02, 0x1b, 0x19,
	0x5a, 0x1b, 0x5d, 0xe1, 0xa4, 0x30, 0xda, 0x69, 0xd1, 0xb9, 0xd2, 0xa6, 0x88, 0xc7, 0xef, 0x00,
	0xce, 0x22, 0x37, 0x3b, 0xd5, 0xf9, 0x65, 0x7a, 0x25, 0x24, 0xf4, 0x12, 0x9d, 0x45, 0x69, 0x6e,
	0x65, 0xf3, 0x59, 0xeb, 0x60, 0xa0, 0x16, 0xae, 0xd8, 0x81, 0x4e, 0xe1, 0xf3, 0xac, 0x6c, 0x31,
	0x1e, 0x9c, 0xf1, 0x2b, 0xe8, 0x56, 0xcc, 0x7d, 0xe8, 0x98, 0xf2, 0x06, 0x03, 0x6f, 0x78, 0xb8,
	0x3d, 0xe1, 0xe3, 0x27, 0xab, 0xb3, 0x55, 0x88, 0x8f, 0x23, 0xd8, 0x3c, 0x77, 0x91, 0x2b, 0xad,
	0x42, 0x5b, 0xe8, 0xdc, 0xa2, 0x78, 0x0a, 0xc3, 0xd2, 0xff, 0x26, 0xd3, 0xfa, 0x07, 0x80, 0x21,
	0xa2, 0xdb, 0x7a, 0x55, 0xed, 0x3f, 0x54, 0xd5, 0xa9, 0x57, 0xf5, 0xb3, 0x0b, 0x3d, 0x85, 0x5f,
	0x4b, 0xb4, 0x8e, 0xb8, 0xb7, 0x68, 0x6c, 0xaa, 0x73, 0x5f, 0x59, 0x83, 0xb8, 0x95, 0x2b, 0x36,
	0xa1, 0x99, 0x26, 0xfe, 0x6b, 0x8d, 0x83, 0xb6, 0xf2, 0x96, 0xd8, 0x82, 0x56, 0x69, 0x52, 0xff,
	0x85, 0xc6, 0xc1, 0x48, 0x91, 0x29, 0x1e, 0x41, 0x37, 0x43, 0x37, 0xd3, 0x89, 0x3f, 0x9e, 0xa8,
	0x95, 0x27, 0x04, 0xb4, 0x2f, 0x74, 0x32, 0x97, 0x5d, 0x4e, 0x65, 0x5b, 0x3c, 0x87, 0x51, 0xac,
	0x73, 0x87, 0xb9, 0x9b, 0xba, 0x79, 0x81, 0xb2, 0xc7, 0x8c, 0x61, 0x85, 0x7d, 0xf1, 0x90, 0x78,
	0x02, 0x50, 0x5a, 0x34, 0x53, 0xff, 0x06, 0xb9, 0x93, 0x7d, 0x26, 0x0f, 0x08, 0x39, 0x21, 0x40,
	0x1c, 0x42, 0x37, 0xd6, 0xfa, 0x3a, 0x45, 0x39, 0xe0, 0x16, 0xee, 0x56, 0x2d, 0xac, 0x6e, 0x32,
	0x39, 0xe5, 0xe0, 0xfb, 0xdc, 0x99, 0xb9, 0xaa, 0x32, 0x89, 0x33, 0xc3, 0x28, 0x41, 0x23, 0xe1,
	0x4e, 0xce, 0x47, 0x0e, 0x56, 0x9c, 0x90, 0x49, 0xed, 0x36, 0x98, 0x69, 0x87, 0xd3, 0x28, 0x49,
	0x8c, 0x1c, 0x72, 0xa1, 0x10, 0xa0, 0x13, 0x8f, 0x50, 0xcb, 0x0c, 0x5e, 0xa2, 0xf1, 0xa7, 0x8e,
	0x42, 0xcb, 0x2a, 0x57, 0xec, 0x42, 0xdf, 0x60, 0x8c, 0xe9, 0x2d, 0x26, 0xf2, 0x81, 0x0f, 0xb5,
	0xd4, 0xd2, 0xa7, 0xa6, 0x50, 0xf7, 0xe5, 0x16, 0x53, 0xd8, 0x26, 0x6c, 0xa6, 0xad, 0x93, 0xdb,
	0x01, 0x23, 0x5b, 0xbc, 0x80, 0xf6, 0xa5, 0x36, 0x99, 0x14, 0x5c, 0xb0, 0x5c, 0x2b, 0xf8, 0x83,
	0x0f, 0x85, 0x72, 0x39, 0x4b, 0xbc, 0x84, 0x8e, 0x0f, 0x98, 0xb9, 0x7c, 0xc8, 0xe9, 0x8f, 0xd7,
	0xd2, 0x3f, 0x53, 0x2c, 0xe4, 0x87, 0x3c, 0x22, 0x14, 0x91, 0x89, 0x32, 0xb9, 0x73, 0x27, 0xe1,
	0x8c, 0x62, 0x15, 0x81, 0xf3, 0x76, 0xdf, 0xc0, 0xb0, 0xd6, 0x59, 0x9a, 0x82, 0x6b, 0x9c, 0xcb,
	0x06, 0x57, 0x4c, 0x26, 0xcd, 0xd8, 0x6d, 0x74, 0x53, 0x22, 0xcf, 0xcf, 0x48, 0x05, 0xe7, 0x6d,
	0xf3, 0xb8, 0x41, 0xd4, 0x5a, 0x83, 0xef, 0x45, 0x7d, 0x0d, 0x83, 0xe5, 0x55, 0xef, 0x45, 0x3c,
	0x06, 0x58, 0x5d, 0xfa, 0xbe, 0xcc, 0xd5, 0xed, 0xff, 0xc6, 0x1c, 0xd4, 0x98, 0xe3, 0x1f, 0x4d,
	0xe8, 0x2f, 0xd5, 0xfa, 0xef, 0x82, 0xf2, 0x83, 0x66, 0x59, 0xe9, 0xd3, 0x58, 0x27, 0xc8, 0xc2,
	0xea, 0x28, 0x08, 0xd0, 0xa9, 0x47, 0x96, 0x3a, 0xea, 0xd4, 0x74, 0xe4, 0xab, 0x40, 0x63, 0xb4,
	0xf1, 0x22, 0xe0, 0x2a, 0xd8, 0x11, 0x47, 0x6b, 0x73, 0xbe, 0xb7, 0x7c, 0xd6, 0x50, 0xd5, 0x9d,
	0x83, 0xbe, 0x2e, 0xc9, 0xe1, 0xef, 0x92, 0xdc, 0x87, 0x5e, 0x50, 0x92, 0xf5, 0xa3, 0x4e, 0x07,
	0x6f, 0x54, 0x07, 0x87, 0x91, 0x50, 0x8b, 0xe8, 0x7f, 0x3c, 0xf5, 0xf8, 0x7b, 0x83, 0x96, 0x24,
	0xcb, 0xd5, 0x5f, 0x38, 0x8f, 0xb2, 0x45, 0x87, 0xd9, 0x5e, 0x11, 0x5b, 0x35, 0xe2, 0x52, 0x4d,
	0xed, 0x9a, 0x9a, 0xfc, 0x3a, 0x0a, 0x7b, 0x6f, 0xb1, 0x8e, 0x82, 0x47, 0x7d, 0xc6, 0x6f, 0x45,
	0x6a, 0xfc, 0x06, 0xb5, 0x18, 0xf3, 0x56, 0x6a, 0x29, 0xa8, 0xa0, 0x73, 0x8c, 0x89, 0xe8, 0x03,
	0xa5, 0x41, 0x5e, 0x3a, 0x7d, 0x55, 0x79, 0x62, 0x0f, 0x06, 0x33, 0xe7, 0x8a, 0xa9, 0xce, 0x6f,
	0xe6, 0xdc, 0xef, 0xbe, 0xea, 0x13, 0xf0, 0xc9, 0xfb, 0x17, 0x5d, 0xfe, 0x9b, 0x38, 0xfa, 0x15,
	0x00, 0x00, 0xff, 0xff, 0x95, 0xf8, 0x70, 0x15, 0x37, 0x06, 0x00, 0x00,
}
