// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package gorpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusResponse struct {
	Domains              []string `protobuf:"bytes,4,rep,name=domains,proto3" json:"domains,omitempty"`
	Paths                []string `protobuf:"bytes,5,rep,name=paths,proto3" json:"paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_056d78b463eef8d2, []int{0}
}
func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (dst *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(dst, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetDomains() []string {
	if m != nil {
		return m.Domains
	}
	return nil
}

func (m *StatusResponse) GetPaths() []string {
	if m != nil {
		return m.Paths
	}
	return nil
}

type Request struct {
	Version              string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Id                   uint64            `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Uri                  []byte            `protobuf:"bytes,4,opt,name=uri,proto3" json:"uri,omitempty"`
	Method               string            `protobuf:"bytes,5,opt,name=method,proto3" json:"method,omitempty"`
	Body                 []byte            `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	UserAgent            []byte            `protobuf:"bytes,8,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	Cookie               map[string][]byte `protobuf:"bytes,9,rep,name=cookie,proto3" json:"cookie,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Header               map[string][]byte `protobuf:"bytes,10,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RemoteAddr           string            `protobuf:"bytes,11,opt,name=remote_addr,json=remoteAddr,proto3" json:"remote_addr,omitempty"`
	Referer              string            `protobuf:"bytes,12,opt,name=referer,proto3" json:"referer,omitempty"`
	Received             int64             `protobuf:"varint,15,opt,name=received,proto3" json:"received,omitempty"`
	Path                 string            `protobuf:"bytes,16,opt,name=path,proto3" json:"path,omitempty"`
	Host                 string            `protobuf:"bytes,17,opt,name=host,proto3" json:"host,omitempty"`
	Form1                map[string][]byte `protobuf:"bytes,18,rep,name=form1,proto3" json:"form1,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Query1               map[string][]byte `protobuf:"bytes,19,rep,name=query1,proto3" json:"query1,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Form                 map[string]string `protobuf:"bytes,20,rep,name=form,proto3" json:"form,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Query                map[string]string `protobuf:"bytes,21,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_056d78b463eef8d2, []int{1}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Request) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Request) GetUri() []byte {
	if m != nil {
		return m.Uri
	}
	return nil
}

func (m *Request) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Request) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Request) GetUserAgent() []byte {
	if m != nil {
		return m.UserAgent
	}
	return nil
}

func (m *Request) GetCookie() map[string][]byte {
	if m != nil {
		return m.Cookie
	}
	return nil
}

func (m *Request) GetHeader() map[string][]byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Request) GetRemoteAddr() string {
	if m != nil {
		return m.RemoteAddr
	}
	return ""
}

func (m *Request) GetReferer() string {
	if m != nil {
		return m.Referer
	}
	return ""
}

func (m *Request) GetReceived() int64 {
	if m != nil {
		return m.Received
	}
	return 0
}

func (m *Request) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Request) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Request) GetForm1() map[string][]byte {
	if m != nil {
		return m.Form1
	}
	return nil
}

func (m *Request) GetQuery1() map[string][]byte {
	if m != nil {
		return m.Query1
	}
	return nil
}

func (m *Request) GetForm() map[string]string {
	if m != nil {
		return m.Form
	}
	return nil
}

func (m *Request) GetQuery() map[string]string {
	if m != nil {
		return m.Query
	}
	return nil
}

type Response struct {
	Version              string            `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Id                   uint64            `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	StatusCode           int32             `protobuf:"varint,4,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Body                 []byte            `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Header               map[string][]byte `protobuf:"bytes,10,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Cookies              []*Cookie         `protobuf:"bytes,12,rep,name=cookies,proto3" json:"cookies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_056d78b463eef8d2, []int{2}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Response) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Response) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *Response) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Response) GetHeader() map[string][]byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Response) GetCookies() []*Cookie {
	if m != nil {
		return m.Cookies
	}
	return nil
}

type Cookie struct {
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Path                 string   `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	Domain               string   `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	ExpiredSec           int64    `protobuf:"varint,6,opt,name=expired_sec,json=expiredSec,proto3" json:"expired_sec,omitempty"`
	Secure               bool     `protobuf:"varint,8,opt,name=secure,proto3" json:"secure,omitempty"`
	HttpOnly             bool     `protobuf:"varint,9,opt,name=http_only,json=httpOnly,proto3" json:"http_only,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cookie) Reset()         { *m = Cookie{} }
func (m *Cookie) String() string { return proto.CompactTextString(m) }
func (*Cookie) ProtoMessage()    {}
func (*Cookie) Descriptor() ([]byte, []int) {
	return fileDescriptor_message_056d78b463eef8d2, []int{3}
}
func (m *Cookie) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cookie.Unmarshal(m, b)
}
func (m *Cookie) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cookie.Marshal(b, m, deterministic)
}
func (dst *Cookie) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cookie.Merge(dst, src)
}
func (m *Cookie) XXX_Size() int {
	return xxx_messageInfo_Cookie.Size(m)
}
func (m *Cookie) XXX_DiscardUnknown() {
	xxx_messageInfo_Cookie.DiscardUnknown(m)
}

var xxx_messageInfo_Cookie proto.InternalMessageInfo

func (m *Cookie) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Cookie) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Cookie) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Cookie) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *Cookie) GetExpiredSec() int64 {
	if m != nil {
		return m.ExpiredSec
	}
	return 0
}

func (m *Cookie) GetSecure() bool {
	if m != nil {
		return m.Secure
	}
	return false
}

func (m *Cookie) GetHttpOnly() bool {
	if m != nil {
		return m.HttpOnly
	}
	return false
}

func init() {
	proto.RegisterType((*StatusResponse)(nil), "gorpc.StatusResponse")
	proto.RegisterType((*Request)(nil), "gorpc.Request")
	proto.RegisterMapType((map[string][]byte)(nil), "gorpc.Request.CookieEntry")
	proto.RegisterMapType((map[string][]byte)(nil), "gorpc.Request.Form1Entry")
	proto.RegisterMapType((map[string]string)(nil), "gorpc.Request.FormEntry")
	proto.RegisterMapType((map[string][]byte)(nil), "gorpc.Request.HeaderEntry")
	proto.RegisterMapType((map[string][]byte)(nil), "gorpc.Request.Query1Entry")
	proto.RegisterMapType((map[string]string)(nil), "gorpc.Request.QueryEntry")
	proto.RegisterType((*Response)(nil), "gorpc.Response")
	proto.RegisterMapType((map[string][]byte)(nil), "gorpc.Response.HeaderEntry")
	proto.RegisterType((*Cookie)(nil), "gorpc.Cookie")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_message_056d78b463eef8d2) }

var fileDescriptor_message_056d78b463eef8d2 = []byte{
	// 599 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x54, 0xcf, 0x6e, 0x13, 0x3f,
	0x10, 0x56, 0xfe, 0x6c, 0x92, 0x9d, 0xb4, 0xfd, 0xf5, 0x67, 0x0a, 0x32, 0xad, 0x10, 0x55, 0x2e,
	0xf4, 0x80, 0x82, 0xda, 0x1e, 0x28, 0x9c, 0xa8, 0x2a, 0x10, 0x37, 0x84, 0xfb, 0x00, 0xd1, 0x76,
	0x77, 0xda, 0xac, 0xda, 0x5d, 0x2f, 0xb6, 0xb7, 0x22, 0x57, 0xde, 0x82, 0xf7, 0xe0, 0x01, 0xf1,
	0x8c, 0x37, 0xe9, 0xaa, 0x8a, 0x04, 0x11, 0xb7, 0x99, 0x6f, 0xe6, 0xb3, 0x67, 0xc6, 0xfe, 0x06,
	0xb6, 0x0b, 0xb4, 0x36, 0xb9, 0xc1, 0x69, 0x65, 0xb4, 0xd3, 0x22, 0xba, 0xd1, 0xa6, 0x4a, 0x27,
	0x1f, 0x60, 0xe7, 0xd2, 0x25, 0xae, 0xb6, 0x0a, 0x6d, 0xa5, 0x4b, 0x8b, 0x42, 0xc2, 0x30, 0xd3,
	0x45, 0x92, 0x97, 0x56, 0xf6, 0x0f, 0x7b, 0x47, 0xb1, 0x5a, 0xba, 0x62, 0x0f, 0xa2, 0x2a, 0x71,
	0x73, 0x2b, 0x23, 0xc6, 0x83, 0x33, 0xf9, 0x39, 0x84, 0xa1, 0xc2, 0x6f, 0x35, 0x5a, 0x47, 0xdc,
	0x7b, 0x34, 0x36, 0xd7, 0xa5, 0xec, 0x1e, 0x76, 0x88, 0xdb, 0xb8, 0x62, 0x07, 0xba, 0x79, 0x26,
	0x7b, 0x1e, 0xec, 0x2b, 0x6f, 0x89, 0x5d, 0xe8, 0xd5, 0x26, 0xf7, 0x37, 0x74, 0x8e, 0xb6, 0x14,
	0x99, 0xe2, 0x19, 0x0c, 0x0a, 0x74, 0x73, 0x9d, 0xf9, 0xe3, 0x89, 0xda, 0x78, 0x42, 0x40, 0xff,
	0x4a, 0x67, 0x0b, 0x39, 0xe0, 0x54, 0xb6, 0xc5, 0x0b, 0x80, 0xda, 0xa2, 0x99, 0xf9, 0x76, 0x4a,
	0x27, 0x47, 0x1c, 0x89, 0x09, 0x39, 0x27, 0x40, 0x9c, 0xc0, 0x20, 0xd5, 0xfa, 0x36, 0x47, 0x19,
	0xfb, 0x4a, 0xc7, 0x27, 0xfb, 0x53, 0x6e, 0x76, 0xda, 0x94, 0x39, 0xbd, 0xe0, 0xe0, 0xc7, 0xd2,
	0x99, 0x85, 0x6a, 0x32, 0x89, 0x33, 0xc7, 0x24, 0x43, 0x23, 0x61, 0x2d, 0xe7, 0x33, 0x07, 0x1b,
	0x4e, 0xc8, 0x14, 0x2f, 0x61, 0x6c, 0xb0, 0xd0, 0x0e, 0x67, 0x49, 0x96, 0x19, 0x39, 0xe6, 0xba,
	0x21, 0x40, 0xe7, 0x1e, 0xa1, 0x79, 0x18, 0xbc, 0x46, 0xe3, 0x4f, 0xdd, 0x0a, 0xf3, 0x68, 0x5c,
	0xb1, 0x0f, 0x23, 0x83, 0x29, 0xe6, 0xf7, 0x98, 0xc9, 0xff, 0x7c, 0xa8, 0xa7, 0x56, 0x3e, 0x75,
	0x4c, 0xa3, 0x95, 0xbb, 0x4c, 0x61, 0x9b, 0xb0, 0xb9, 0xb6, 0x4e, 0xfe, 0x1f, 0x30, 0xb2, 0xc5,
	0x1b, 0x88, 0xae, 0xb5, 0x29, 0x8e, 0xa5, 0xe0, 0x8a, 0x9f, 0x3f, 0xaa, 0xf8, 0x13, 0xc5, 0x42,
	0xc1, 0x21, 0x8f, 0x7a, 0xf4, 0x21, 0xb3, 0x38, 0x96, 0x4f, 0xd6, 0xf6, 0xf8, 0x95, 0x83, 0x4d,
	0x8f, 0x21, 0x53, 0xbc, 0x86, 0x3e, 0x91, 0xe5, 0x1e, 0x33, 0xe4, 0x9a, 0x3b, 0x42, 0x3e, 0x67,
	0x51, 0x49, 0xcc, 0x93, 0x4f, 0xd7, 0x96, 0xc4, 0x17, 0x34, 0x25, 0x71, 0xde, 0xfe, 0x3b, 0x18,
	0xb7, 0x5e, 0x83, 0xbe, 0xc5, 0x2d, 0x2e, 0x64, 0x87, 0xbb, 0x24, 0x93, 0x3e, 0xdd, 0x7d, 0x72,
	0x57, 0x23, 0x7f, 0xa8, 0x2d, 0x15, 0x9c, 0xf7, 0xdd, 0xb3, 0x0e, 0x51, 0x5b, 0x8f, 0xb2, 0x11,
	0xf5, 0x0c, 0xe0, 0x61, 0x3a, 0x9b, 0x5e, 0xda, 0x9a, 0xd2, 0x46, 0xd4, 0xb7, 0x10, 0xaf, 0xc6,
	0xf5, 0x27, 0x62, 0xfc, 0xa8, 0xda, 0x87, 0xc1, 0x6d, 0xc2, 0x9c, 0xfc, 0xe8, 0xc2, 0xa8, 0x2d,
	0xec, 0xbf, 0x14, 0xa7, 0xff, 0xd7, 0x96, 0x97, 0xc2, 0x2c, 0xd5, 0x19, 0xb2, 0x48, 0x23, 0x05,
	0x01, 0xba, 0xf0, 0xc8, 0x4a, 0x93, 0x51, 0x4b, 0x93, 0xa7, 0x8f, 0x04, 0x74, 0xb0, 0x7a, 0xfb,
	0x70, 0xff, 0x5a, 0x05, 0xbd, 0x82, 0x61, 0xd0, 0x9f, 0xf5, 0x02, 0x21, 0xd6, 0x76, 0xc3, 0x0a,
	0x9f, 0x42, 0x2d, 0xa3, 0xff, 0xf0, 0xd8, 0x93, 0x5f, 0x1d, 0x18, 0x84, 0xe3, 0xa8, 0xee, 0x32,
	0x29, 0x96, 0x83, 0x62, 0xfb, 0x81, 0xd8, 0x6b, 0x11, 0x57, 0x1a, 0xec, 0xb7, 0x34, 0xe8, 0x37,
	0x54, 0x58, 0x85, 0xcb, 0x0d, 0x15, 0x3c, 0x1a, 0x17, 0x7e, 0xaf, 0x72, 0x83, 0xd9, 0xcc, 0x62,
	0xca, 0x8b, 0xaa, 0xa7, 0xa0, 0x81, 0x2e, 0x31, 0x25, 0xa2, 0x0f, 0xd4, 0x06, 0x79, 0x55, 0x8d,
	0x54, 0xe3, 0x89, 0x03, 0x88, 0xe7, 0xce, 0x55, 0x33, 0x5d, 0xde, 0x2d, 0xfc, 0xaa, 0xa2, 0xd0,
	0x88, 0x80, 0x2f, 0xde, 0xbf, 0x1a, 0xf0, 0x9e, 0x3e, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x1b,
	0xc1, 0xd5, 0xcf, 0xb8, 0x05, 0x00, 0x00,
}
